language: generic

# super user permissions in order execute this build
sudo: required

# Tell Travis what we want to do with our code --------------------------------------------
services:
  # need `docker-cli` preinstalled: automatically install copy of docker into running container
  - docker

before_install:
  # Build image of only client to test using Dockerfile.dev
  - docker build -t "$DOCKER_ID"/react-test -f ./client/Dockerfile.dev ./client

script:
  # How to test using created image ~react-test`
  - docker run -e CI=true "$DOCKER_ID"/react-test npm test -- --coverage

after_success:
  # build prod versions of all projects
  - docker build -t "$DOCKER_ID"/multi-client ./client
  - docker build -t "$DOCKER_ID"/multi-nginx ./nginx
  - docker build -t "$DOCKER_ID"/multi-server ./server
  - docker build -t "$DOCKER_ID"/multi-worker ./worker
  # log in to the Docker CLI
  - echo "$DOCKER_PSWD" | docker login -u "$DOCKER_ID" --password-stdin
  # push all created images to DockerHub
  - docker push "$DOCKER_ID"/multi-client
  - docker push "$DOCKER_ID"/multi-nginx
  - docker push "$DOCKER_ID"/multi-server
  - docker push "$DOCKER_ID"/multi-worker