language: generic

# super user permissions in order execute this build
sudo: required

# Tell Travis what we want to do with our code --------------------------------------------
services:
  # need `docker-cli` preinstalled: automatically install copy of docker into running container
  - docker

before_install:
  # Build image of only client to test using Dockerfile.dev
  - docker build -t sashagloo/react-test -f ./client/Dockerfile.dev ./client

script:
  # How to test using created image ~react-test`
  - docker run -e CI=true sashagloo/react-test npm test -- --coverage
#  - docker run -e CI=true sashagloo/react-test npm run test  -- --coverage

after_success:
  # build prod versions of all projects
  - docker build -t sashagloo/multi-client ./client
  - docker build -t sashagloo/multi-nginx ./nginx
  - docker build -t sashagloo/multi-server ./server
  - docker build -t sashagloo/multi-worker ./worker
  # log in to the Docker CLI
  - echo "$DOCKER_PSWD" | docker login -u "$DOCKER_ID" --password-stdin
  # push all created images to DockerHub
  - docker push sashagloo/multi-client
  - docker push sashagloo/multi-nginx
  - docker push sashagloo/multi-server
  - docker push sashagloo/multi-worker